// Generated by CoffeeScript 1.3.3
var Application, Compiler, coffee, directory, fs, jade, match, path, sty;

fs = require("fs");

path = require("path");

match = require("match-files");

coffee = require("coffee-script");

jade = require("jade");

sty = require('sty');

directory = process.cwd();

console.info = function(msg) {
  return console.log(sty.red(msg));
};

console.debug = function(msg) {
  return console.log(sty.green(msg));
};

Application = (function() {
  var getFileType;

  function Application() {
    this.program = require('commander');
    this.titanium = null;
    this.program.version('0.0.2').option('-s, --setup', 'Setup lazy-alloy directory structure.').option('-c, --compile', 'Just compile.').option('-w, --watch', 'Watch file changes & compile.').option('-p, --platform [platform]', 'Run titanium on `platform`').option('-d, --directory [dirname]', 'Set source directory (default `src/`)').parse(process.argv);
    this.subfolder = this.program.directory || 'src/';
    this.compiler = new Compiler(this.subfolder);
    if (this.program.setup) {
      return this.setup();
    }
    if (this.program.compile) {
      return this.compile();
    }
    if (this.program.watch) {
      return this.watch();
    }
    if (this.program.platform) {
      return this.build();
    }
    console.info("nothing to do!");
  }

  Application.prototype.compile = function() {
    return this.compiler.all();
  };

  Application.prototype.build = function() {
    var alloy, exec, spawn,
      _this = this;
    spawn = require("child_process").spawn;
    exec = require("child_process").exec;
    if (this.titanium !== null) {
      console.info("stopping titanium...");
      this.titanium.kill();
    }
    alloy = exec("alloy compile", function(error, stdout, stderr) {
      if (stdout) {
        console.debug(stdout);
      }
      if (stderr) {
        return console.log(stderr);
      }
    });
    return alloy.on('exit', function(code) {
      console.log("alloy stopped with code " + code);
      if (code !== 1) {
        console.info("starting titanium...");
        _this.titanium = spawn("titanium", ["build", "-p", _this.program.platform]);
        _this.titanium.stdout.on("data", function(data) {
          return console.log("titanium: " + data);
        });
        _this.titanium.stderr.on("data", function(data) {
          return console.log("titanium: " + data);
        });
        return _this.titanium.on("exit", function(code) {
          return console.log("titanium exited with code " + code);
        });
      }
    });
  };

  Application.prototype.watch = function() {
    var watchr,
      _this = this;
    watchr = require("watchr");
    console.info("Waiting for file change...");
    watchr.watch({
      paths: [directory],
      listeners: {
        error: function(err) {
          return console.log("an error occured:", err);
        },
        change: function(changeType, filePath, fileCurrentStat, filePreviousStat) {
          var file;
          if (changeType !== "create" && changeType !== "update") {
            return;
          }
          file = getFileType(filePath);
          if (!file) {
            return;
          }
          _this.compiler.files([filePath], file.fromTo[0], file.fromTo[1]);
          if (_this.program.platform) {
            return _this.build();
          }
        }
      }
    });
    return {
      next: function(err, watchers) {
        if (err) {
          return console.log("watching everything failed with error", err);
        } else {
          return console.debug("Waiting for file change...");
        }
      }
    };
  };

  Application.prototype.setup = function() {
    if (this.subfolder.charAt(this.subfolder.length - 1) !== '/') {
      this.subfolder += '/';
    }
    console.info('Setting up folder structure...');
    this.compiler.mkdirSync(this.subfolder);
    this.compiler.mkdirSync(this.subfolder + 'views');
    this.compiler.mkdirSync(this.subfolder + 'styles');
    this.compiler.mkdirSync(this.subfolder + 'controllers');
    return console.debug('Setup complete.');
  };

  getFileType = function(path) {
    var inpath;
    inpath = function(name) {
      return !!~path.indexOf(name);
    };
    if (inpath(".jade")) {
      return {
        type: "view",
        fromTo: ["jade", "xml"]
      };
    }
    if (!inpath(".coffee")) {
      return null;
    }
    if (inpath("styles/")) {
      return {
        type: "style",
        fromTo: ["coffee", "tss"]
      };
    }
    if (inpath("alloy.coffee")) {
      return {
        type: "alloy",
        fromTo: ["coffee", "js"]
      };
    }
    if (inpath("controllers/")) {
      return {
        type: "controller",
        fromTo: ["coffee", "js"]
      };
    }
  };

  return Application;

})();

Compiler = (function() {

  Compiler.prototype.logger = console;

  function Compiler(subfolder) {
    this.subfolder = subfolder != null ? subfolder : 'src/';
  }

  Compiler.prototype.views = function() {
    return this.process("views/", "jade", "xml");
  };

  Compiler.prototype.controllers = function() {
    return this.process("controllers/", "coffee", "js");
  };

  Compiler.prototype.styles = function() {
    return this.process("styles/", "coffee", "tss");
  };

  Compiler.prototype.all = function() {
    this.views();
    this.controllers();
    return this.styles();
  };

  Compiler.prototype.process = function(path, from, to) {
    var filter,
      _this = this;
    path = this.subfolder + path;
    this.logger.info("Preprocessing " + from + " files in " + path);
    filter = function(dir) {
      return dir.indexOf("." + from) !== -1;
    };
    return match.find(process.cwd() + "/" + path, {
      fileFilters: [filter]
    }, function(err, files) {
      return _this.files(files, from, to);
    });
  };

  Compiler.prototype.file = function(from, output, type) {
    var compiled, data;
    this.logger.debug("Building " + type + ": " + from + " --> " + output);
    data = fs.readFileSync(from, 'utf8');
    compiled = this.build[type](data);
    return fs.writeFileSync(output, compiled, 'utf8');
  };

  Compiler.prototype.files = function(files, from, to, to_path) {
    var file, output, _i, _len, _results;
    if (files.length === 0) {
      return this.logger.debug("No '*." + from + "' files need to preprocess.. " + files.length + " files");
    }
    _results = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      if (!!~file.indexOf("lazyalloy")) {
        break;
      }
      output = file.substring(0, file.length - from.length).toString() + to;
      output = output.replace(new RegExp('(.*)' + this.subfolder), '$1app/');
      _results.push(this.file(file, output, to));
    }
    return _results;
  };

  Compiler.prototype.mkdir = function(path) {
    if (fs.existsSync(path)) {
      return console.debug("" + path + " already exists, doing nothing");
    } else {
      return fs.mkdirSync(path);
    }
  };

  Compiler.prototype.build = {
    xml: function(data) {
      return jade.compile(data, {
        pretty: true
      })(this);
    },
    tss: function(data) {
      data = this.js(data);
      return (data.replace("};", "")).replace("var tss;\n\ntss = {\n", "");
    },
    js: function(data) {
      return coffee.compile(data.toString(), {
        bare: true
      });
    }
  };

  return Compiler;

})();

module.exports = new Application;
